/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthedRouteImport } from './routes/_authed'
import { Route as ForgotPasswordRouteImport } from './routes/forgot-password'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as SignInRouteImport } from './routes/sign-in'
import { Route as SignUpRouteImport } from './routes/sign-up'
import { Route as AuthedAdminRouteImport } from './routes/_authed/admin'
import { Route as AuthedDashboardRouteImport } from './routes/_authed/dashboard'
import { Route as DevHealthRouteImport } from './routes/dev/health'
import { Route as InviteTokenRouteImport } from './routes/invite.$token'
import { Route as AuthedContentOrgIdRouteImport } from './routes/_authed/content.$orgId'
import { Route as AuthedWorkspaceOrgIdRouteImport } from './routes/_authed/workspace.$orgId'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'
import { Route as ApiMediaItemIdRouteImport } from './routes/api/media/$itemId'
import { Route as ApiTelegramWebhookRouteImport } from './routes/api/telegram/webhook'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthedRoute = AuthedRouteImport.update({
  id: '/_authed',
  getParentRoute: () => rootRouteImport,
} as any)
const ForgotPasswordRoute = ForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const SignInRoute = SignInRouteImport.update({
  id: '/sign-in',
  path: '/sign-in',
  getParentRoute: () => rootRouteImport,
} as any)
const SignUpRoute = SignUpRouteImport.update({
  id: '/sign-up',
  path: '/sign-up',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthedAdminRoute = AuthedAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedDashboardRoute = AuthedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthedRoute,
} as any)
const DevHealthRoute = DevHealthRouteImport.update({
  id: '/dev/health',
  path: '/dev/health',
  getParentRoute: () => rootRouteImport,
} as any)
const InviteTokenRoute = InviteTokenRouteImport.update({
  id: '/invite/$token',
  path: '/invite/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthedContentOrgIdRoute = AuthedContentOrgIdRouteImport.update({
  id: '/content/$orgId',
  path: '/content/$orgId',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedWorkspaceOrgIdRoute = AuthedWorkspaceOrgIdRouteImport.update({
  id: '/workspace/$orgId',
  path: '/workspace/$orgId',
  getParentRoute: () => AuthedRoute,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiMediaItemIdRoute = ApiMediaItemIdRouteImport.update({
  id: '/api/media/$itemId',
  path: '/api/media/$itemId',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiTelegramWebhookRoute = ApiTelegramWebhookRouteImport.update({
  id: '/api/telegram/webhook',
  path: '/api/telegram/webhook',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/reset-password': typeof ResetPasswordRoute
  '/sign-in': typeof SignInRoute
  '/sign-up': typeof SignUpRoute
  '/admin': typeof AuthedAdminRoute
  '/dashboard': typeof AuthedDashboardRoute
  '/dev/health': typeof DevHealthRoute
  '/invite/$token': typeof InviteTokenRoute
  '/content/$orgId': typeof AuthedContentOrgIdRoute
  '/workspace/$orgId': typeof AuthedWorkspaceOrgIdRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/media/$itemId': typeof ApiMediaItemIdRoute
  '/api/telegram/webhook': typeof ApiTelegramWebhookRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/reset-password': typeof ResetPasswordRoute
  '/sign-in': typeof SignInRoute
  '/sign-up': typeof SignUpRoute
  '/admin': typeof AuthedAdminRoute
  '/dashboard': typeof AuthedDashboardRoute
  '/dev/health': typeof DevHealthRoute
  '/invite/$token': typeof InviteTokenRoute
  '/content/$orgId': typeof AuthedContentOrgIdRoute
  '/workspace/$orgId': typeof AuthedWorkspaceOrgIdRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/media/$itemId': typeof ApiMediaItemIdRoute
  '/api/telegram/webhook': typeof ApiTelegramWebhookRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authed': typeof AuthedRouteWithChildren
  '/forgot-password': typeof ForgotPasswordRoute
  '/reset-password': typeof ResetPasswordRoute
  '/sign-in': typeof SignInRoute
  '/sign-up': typeof SignUpRoute
  '/_authed/admin': typeof AuthedAdminRoute
  '/_authed/dashboard': typeof AuthedDashboardRoute
  '/dev/health': typeof DevHealthRoute
  '/invite/$token': typeof InviteTokenRoute
  '/_authed/content/$orgId': typeof AuthedContentOrgIdRoute
  '/_authed/workspace/$orgId': typeof AuthedWorkspaceOrgIdRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/media/$itemId': typeof ApiMediaItemIdRoute
  '/api/telegram/webhook': typeof ApiTelegramWebhookRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/forgot-password'
    | '/reset-password'
    | '/sign-in'
    | '/sign-up'
    | '/admin'
    | '/dashboard'
    | '/dev/health'
    | '/invite/$token'
    | '/content/$orgId'
    | '/workspace/$orgId'
    | '/api/auth/$'
    | '/api/media/$itemId'
    | '/api/telegram/webhook'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/forgot-password'
    | '/reset-password'
    | '/sign-in'
    | '/sign-up'
    | '/admin'
    | '/dashboard'
    | '/dev/health'
    | '/invite/$token'
    | '/content/$orgId'
    | '/workspace/$orgId'
    | '/api/auth/$'
    | '/api/media/$itemId'
    | '/api/telegram/webhook'
  id:
    | '__root__'
    | '/'
    | '/_authed'
    | '/forgot-password'
    | '/reset-password'
    | '/sign-in'
    | '/sign-up'
    | '/_authed/admin'
    | '/_authed/dashboard'
    | '/dev/health'
    | '/invite/$token'
    | '/_authed/content/$orgId'
    | '/_authed/workspace/$orgId'
    | '/api/auth/$'
    | '/api/media/$itemId'
    | '/api/telegram/webhook'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthedRoute: typeof AuthedRouteWithChildren
  ForgotPasswordRoute: typeof ForgotPasswordRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  SignInRoute: typeof SignInRoute
  SignUpRoute: typeof SignUpRoute
  DevHealthRoute: typeof DevHealthRoute
  InviteTokenRoute: typeof InviteTokenRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
  ApiMediaItemIdRoute: typeof ApiMediaItemIdRoute
  ApiTelegramWebhookRoute: typeof ApiTelegramWebhookRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authed': {
      id: '/_authed'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forgot-password': {
      id: '/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof ForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sign-in': {
      id: '/sign-in'
      path: '/sign-in'
      fullPath: '/sign-in'
      preLoaderRoute: typeof SignInRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sign-up': {
      id: '/sign-up'
      path: '/sign-up'
      fullPath: '/sign-up'
      preLoaderRoute: typeof SignUpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authed/admin': {
      id: '/_authed/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AuthedAdminRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/dashboard': {
      id: '/_authed/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthedDashboardRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/dev/health': {
      id: '/dev/health'
      path: '/dev/health'
      fullPath: '/dev/health'
      preLoaderRoute: typeof DevHealthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/invite/$token': {
      id: '/invite/$token'
      path: '/invite/$token'
      fullPath: '/invite/$token'
      preLoaderRoute: typeof InviteTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authed/content/$orgId': {
      id: '/_authed/content/$orgId'
      path: '/content/$orgId'
      fullPath: '/content/$orgId'
      preLoaderRoute: typeof AuthedContentOrgIdRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/workspace/$orgId': {
      id: '/_authed/workspace/$orgId'
      path: '/workspace/$orgId'
      fullPath: '/workspace/$orgId'
      preLoaderRoute: typeof AuthedWorkspaceOrgIdRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/media/$itemId': {
      id: '/api/media/$itemId'
      path: '/api/media/$itemId'
      fullPath: '/api/media/$itemId'
      preLoaderRoute: typeof ApiMediaItemIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/telegram/webhook': {
      id: '/api/telegram/webhook'
      path: '/api/telegram/webhook'
      fullPath: '/api/telegram/webhook'
      preLoaderRoute: typeof ApiTelegramWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AuthedRouteChildren {
  AuthedAdminRoute: typeof AuthedAdminRoute
  AuthedDashboardRoute: typeof AuthedDashboardRoute
  AuthedContentOrgIdRoute: typeof AuthedContentOrgIdRoute
  AuthedWorkspaceOrgIdRoute: typeof AuthedWorkspaceOrgIdRoute
}

const AuthedRouteChildren: AuthedRouteChildren = {
  AuthedAdminRoute: AuthedAdminRoute,
  AuthedDashboardRoute: AuthedDashboardRoute,
  AuthedContentOrgIdRoute: AuthedContentOrgIdRoute,
  AuthedWorkspaceOrgIdRoute: AuthedWorkspaceOrgIdRoute,
}

const AuthedRouteWithChildren =
  AuthedRoute._addFileChildren(AuthedRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthedRoute: AuthedRouteWithChildren,
  ForgotPasswordRoute: ForgotPasswordRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  SignInRoute: SignInRoute,
  SignUpRoute: SignUpRoute,
  DevHealthRoute: DevHealthRoute,
  InviteTokenRoute: InviteTokenRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
  ApiMediaItemIdRoute: ApiMediaItemIdRoute,
  ApiTelegramWebhookRoute: ApiTelegramWebhookRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
